### PR TITLE
separates width and height for legend squares

### PR DESCRIPTION
**Pull request by CodeCutterUK**

### CODE REVIEW

**Comment by davelandry** [comment]
Love breaking out the width and the height. Could you also rename the current "size" array to "width", as it now only corresponds to the min/max width?

**Comment by CodeCutterUK** [comment]
I was a little worried about introducing a breaking change with a rename like that.....how would that normally be dealt with in D3Plus?

**Comment by davelandry** [comment]
Good point.

What do you think about keeping the "size" key, but adding an optional "width" key that overrides it if it is set (and is just a static Number, not an Array).

**Comment by CodeCutterUK** [comment]
How about expanding the scope of this change.....we could do this:

Allow the current format this would define a box range: `size: [8, 30]`
This can be overloaded with an object, giving a rectangle range:
`size: {
    width: [8, 30],
    height: [8, 10],
}`

**Comment by davelandry** [comment]
I have no problem with that!

**Comment by CodeCutterUK** [comment]
This is probably not relevant to me or the V2 stream of d3plus.....closing down to tidy up a little

**Pull request closed without merging**
